connector.name=iceberg
iceberg.catalog.type=glue
hive.metastore.glue.region=${ENV:AWS_REGION}
hive.metastore.glue.aws-access-key=${ENV:AWS_ACCESS_KEY}
hive.metastore.glue.aws-secret-key=${ENV:AWS_SECRET_KEY}

# Native S3 access
fs.native-s3.enabled=true
s3.region=${ENV:AWS_REGION}
s3.aws-access-key=${ENV:AWS_ACCESS_KEY}
s3.aws-secret-key=${ENV:AWS_SECRET_KEY}
s3.path-style-access=false

# Optional but recommended
iceberg.add-files-procedure.enabled=true